language: c
dist: trusty

before_install:
  - sudo apt-get -qq install gcc-avr gdb-avr avrdude arduino libcppunit-1.13 libcppunit-dev libelf-dev

install:
  - mkdir build && cd build
  - cmake ..

script:
  - make -j 8
